#Lê uma variavel e retorna a classificação dela
A = input('Digite algo:')
print(type(A))
print(A.isalpha())
print(A.isnumeric())
print(A.isalnum())
print(A.islower())
print(A.isupper())
print(A.istitle())
print(A.isspace())